spring.application.name=Usuario_Reservas

spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuarioReservas
spring.datasource.username=postgres
spring.datasource.password=senha-aqui
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
